version: '3.8'

services:
 mariadb:
  image: mariadb
  container_name: raiadb
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  ports:
   - "80:12345"
  networks:
   - examen2
  volumes:
   - mariadb_data:/var/lib/mysql

 php-apache:
  image: php-apache
  container_name: php-apache
  depends_on:
   - mariadb
  ports:
   - "8080:80"
   volumes:
   - ./datos/var/www/html
  networks:
   - examen2

 phpmyadmin:
  image: phpmyadmin
  container_name: phpmyadmin
  depends_on:
   - mariadb
  environment:
   PMA_HOST: mariadb
  ports:
   - "${PMA_PORT}:80"
  networks:
   - examen2


networks:
 examen2
volumens:
 mariadb_data
