openapi: 3.0.4
info:
  title: API de armagedón
  version: 1.0.0
  contact:
   name: Desarrollos Apocalípticos, S.A.
   email: programadores_daw@apocalipsis.com

servers:
 - url: http://www.telearmagedon.com/api/v1
   description: Servidor de Producción
 - url: hhtps://www.desarrollo.telearmagedon.com/api/v1
   description: Servidor de Desarrollo
   
paths:
  /armagedon/:
    get:
      summary: Obtener la lista completa de Armagedones.
      responses:
        '200':
          description: Lista obtenida correctamente.
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: 
                    id: 
                      type: integer
                      description: Identificador de la entidad
                    titulo:
                      type: string
                      description: Título de la entidad