openapi: 3.0.4
info:
  title: API de armagedón
  version: 1.0.0
  contact:
   name: Desarrollos Apocalípticos, S.A.
   email: programadores_daw@apocalipsis.com

servers:
 - url: http://www.telearmagedon.com/api/v1
   description: Servidor de Producción
 - url: hhtps://www.desarrollo.telearmagedon.com/api/v1
   description: Servidor de Desarrollo
   
paths:
  /armagedon/:
    get:
      summary: Obtener la lista completa de Armagedones.
      responses:
        '200':
          description: Lista obtenida correctamente.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Armagedon"
    post:
      summary: Inserta un nuevo recurso Armagedón.
      security:
        - bearerAuth: []        
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Armagedon"
      responses:
        '201':
          description: Recurso creado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: 
                    type: string
                    description: url del recurso creado
                    example: {url: "armagedon/id=42"}
        '400':
          description: Parámetros inválidos
          content:
            text/html:
              schema:
                type: string
                example: "Falta el parámetro id."
        '500':
          description: Error del servidor.
    put:
      summary: ctualiza todos los datos de un recurso Armagedon
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Armagedon"
      responses:
        '200':
          description: Recurso ctualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: 
                    type: string
                    description: url del recurso creado
                    example: " http://localhost/servidorWeb/armagedon/"
        '400':
          description: Parámetros inválidos
          content:
            text/html:
              schema:
                type: string
                example: "Falta el parámetro titulo"
        '500':
          description: Error del servidor.
        
    delete:
      summary: Eliminar el recurso indicado
      parameters:
          - name: id
            in: query
            required: true
            schema:
                type: integer
      responses:
        '204':
          description: Borrado correcto
        '400':
          description: Parámetros inválidos
          content:
            text/html:
              schema:
                type: string
                example: "alta el parámetro id."
        '404':
          description: Recurso no encontrado
          content:
            text/html:
              schema:
                type: string
                example: "No existe un armagedón con ese id."      

components:
  schemas: 
    Armagedon:
      type: object
      properties: 
        id: 
          type: integer
          description: Identificador de la entidad
        bajas:
          type: integer
          minimum: 0
          description: Número de bajas esperadas
        titulo:
          type: string
          description: Título de la entidad
  securitySchemas:
    bearerAuth:
      type: http
      scheme: bearer 
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
        
        
        
        
        
        